# Generated by Django 4.0.1 on 2022-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_status_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminderTime',
            field=models.TimeField(null=True),
        ),
    ]
