# Generated by Django 4.0.1 on 2022-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_remindertime_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
