# Generated by Django 4.0.1 on 2022-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_report_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
